### ISSUE TITLE
SPDX element/relationships should be defined for the container image being described

### ISSUE THREAD

**Issue by lumjjb** [anchore/syft#1241]
**What would you like to be added**:

At the moment, when scanning container image, SPDX documents contain the list of packages that the target contains.. However, there are no elements/relationships that link back to the container that is being described.. 

**Why is this needed**:

Without specifying the container image element/relationships to the packages, the ingestion of SPDX documents resulting in detached packages without being able to query for the containers that use the packages. It will be useful to be able to link them up so that queries can be made for finding entities that use certain packages.

**Additional context**:

Example graph without links to entity:

![image](https://user-images.githubusercontent.com/3060102/193828758-71d0b442-1307-4f24-bda6-8861749ddfb7.png)

The SPDX element to be defined can reference the OCI PURL (https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#oci), and should include sha256 checksum of the container image when possible.

**Comment by spiffcs** [comment]
👋 Nice find @lumjjb! 

As far as the core syft data model do you think this would be a new field for the packages?

https://github.com/anchore/syft/blob/91eece47ffc5de009dccb916458b9ba734864319/schema/json/schema-4.0.0.json#L864-L985

Right now we have a `purl` field that describes the package, but we could add a field that also describes the distro it's related to and then transpose that into the spdx relationship[^1].

We could also codify this as a relationship, but I'm not sure what the parent would be in this case that all packages could be linked back to since we identify the distro as it's own separate field outside of the package list [^2]

[^1]: https://github.com/anchore/syft/blob/91eece47ffc5de009dccb916458b9ba734864319/schema/json/schema-4.0.0.json#L1368-L1390

[^2]: https://github.com/anchore/syft/blob/91eece47ffc5de009dccb916458b9ba734864319/schema/json/schema-4.0.0.json#L755-L814

**Comment by spiffcs** [comment]
Note: I think adding an ID field to the source object might be the best bet here.

We could also potentially update relationships to be `id:container:["id", "id", ...]` so we don't have to generate every single new relationship.

This would give us a good basis for then incorporating 2.3 spdx when it's ready

**Comment by spiffcs** [comment]
@kzantow I think we can also use this issue to discuss changes to the core model that need to be made before we're ready to adopt this for spdx 2.3

**Comment by lumjjb** [comment]
Hi - pinging back on this issue! Wondering if this is something that is being worked on.. We are still special casing this in GUAC and likely will be doing a filter for SBOMs that don't have this soon going forward - as the heuristics are unreliable (sometimes files become containers and vice versa).
