### ISSUE TITLE
FilesAnalyzed wrong and missing SHA1 for files

### ISSUE THREAD

**Issue by vargenau** [anchore/syft#1396]
**Please provide a set of steps on how to reproduce the issue**

```
syft docker:apache/airflow:2.3.0b1-python3.10 -o spdx-tag-value > airflow-syft0.62.3.spdx
```

[airflow-syft0.62.3.spdx.txt](https://github.com/anchore/syft/files/10185371/airflow-syft0.62.3.spdx.txt)

**What happened**:

The SPDX file starts with section ```Unpackaged files```
But ```SPDXRef-1009cda0ea8ddc7a``` shows that file ```/usr/lib/python3.9/asyncio/__main__.py``` is part of package ```libpython3.9-stdlib```

So ```FilesAnalyzed``` should not be ```false``` for this package.

And the mandatory ```SHA1``` is missing for this file.

**What you expected to happen**:

```FilesAnalyzed``` should be ```true``` and the ```SHA1``` should be provided for the files.

**Anything else we need to know?**:

The online validator complains about it:
```
The following warning(s) were raised:
Package at line 33761 invalid: Warning: Found analyzed files for package gpg-agent when analyzedFiles is set to false., 
Package at line 33761 invalid: Missing required SHA1 hashcode value for /usr/bin/gpg-agent in gpg-agent,
Package at line 33761 invalid: Missing required SHA1 hashcode value for /usr/lib/gnupg/gpg-preset-passphrase in gpg-agent,
Package at line 33761 invalid: Missing required SHA1 hashcode value for /usr/lib/gnupg/gpg-protect-tool in gpg-agent,
Package at line 33761 invalid: Missing required SHA1 hashcode value for /etc/X11/Xsession.d/90gpg-agent in gpg-agent,
Package at line 33761 invalid: Missing required SHA1 hashcode value for /etc/logcheck/ignore.d.server/gpg-agent in gpg-agent,
etc.
```

**Environment**:
- Output of `syft version`: 0.62.3
- OS (e.g: `cat /etc/os-release` or similar): Ubuntu 22.10 (Kinetic Kudu)

**Comment by kzantow** [comment]
Hi @vargenau -- I believe you are partially right in your assessment. The `FilesAnalyzed` field has this description:
> Indicates whether the file content of this package has been available for or subjected to analysis when creating the SPDX document. If false, indicates packages that represent metadata or URI references to a project, product, artifact, distribution or a component. If false, the package shall not contain any files. The metadata for the files analyzed field is shown in Table 20.

Syft by default does _not_ read file contents for arbitrary files (in part because this could significantly affect the scan performance). This means that the files included have _not_ been analyzed, which is why this field is set to `false` (the Java cataloger _does_ actually analyze files and this field is `true`, I believe). This is also why there are no SHA1 hashes for said files. The challenge here is that we have 2 options:
1. completely adhere to the SPDX spec -- in which case we would have to remove _all_ the file information from the SBOM because both we've reported this as `FilesAnalyzed: false` and we haven't generated the required SHA1 hashes and we haven't actually analyzed the files
2. generate a slightly non-compliant SPDX file -- this is what we've opted for at present such that the file information we _do_ know about is not completely omitted from the SBOM

Having said this, there is a way to get `SHA1` hashes generated by using these configuration options:
```yaml
file-metadata:
  cataloger:
    # enable/disable cataloging of file metadata
    # SYFT_FILE_METADATA_CATALOGER_ENABLED env var
    enabled: true

  # SYFT_FILE_METADATA_DIGESTS env var
  digests: ["sha1"]
```

Using the environment variables noted in the YAML configuration above would end up something like:
```shell
SYFT_FILE_METADATA_CATALOGER_ENABLED=true SYFT_FILE_METADATA_DIGESTS=sha1 syft docker:apache/airflow:2.3.0b1-python3.10 -o spdx-tag-value
```

However, this doesn't solve the issue about `FilesAnalyzed: false`, as we _still_ are not actually _analyzing_ the files other than just getting a SHA1 hash. Additionally, we would need to then include the `PackageVerificationCode` if we're setting `FilesAnalyzed: true`, which again requires all files to have SHA1 hashes.

We've been thinking about ways to make this work a little more nicely -- for example: _if_ the user outputs SPDX, we automatically enable the SHA1 hashing, but haven't come up with a great solution as of yet. I think the above options should get you closer to what you want, at least.

**Comment by vargenau** [comment]
Hi @kzantow 

Thank you for your detailed explanations.

Yes, it would be good the automatically enable the SHA1 hashing when outputting SPDX. I hope you can find a way to implement it.

**Comment by spiffcs** [comment]
@vargenau after #1418 is merged you should be able to generate documents that pass the online validator. You can also validate documents using tooling provided by the SPDX org

Note: for the `filesAnalyzed` and `packageVerificationCode` fields we are relying on the file digest cataloger producing sha1 sums. Your syft runs will need the following env for those fields to be correct:
```
SYFT_FILE_METADATA_CATALOGER_ENABLED=true SYFT_FILE_METADATA_DIGESTS=sha1
```

**Comment by vargenau** [comment]
Thank you very much.
I confirm that the SPDX result is now valid.
Happy new year 2023!
