### ISSUE TITLE
Turn off SBOM cataloger by default

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#1555]
Today the SBOM cataloger is on by default and has no configurability to select/deselect SBOMs in certain paths,  include/exclude items within SBOMs conditionally, or be able to enrich the package and relationships found in a flexible way. We could consider making the SBOM cataloger opt-in for now until we discover better mechanisms here. This could mean something like this to enable the SBOM cataloger:

```
syft <my-image> --include-sboms
```

There are several options forward here --interested in hearing thoughts here.

**Comment by luhring** [comment]
> We could consider making the SBOM cataloger opt-in for now until we discover better mechanisms here.

Makes sense to me. 👍  I could try taking a stab at this?

**Comment by kzantow** [comment]
Developer note: Since the builder PR landed, the change fairly simple, I think: [updating the SBOM cataloger line](https://github.com/anchore/syft/blob/main/internal/task/package_tasks.go#L118) to remove the `pkgcataloging.ImageTag, pkgcataloging.DeclaredTag, pkgcataloging.DirectoryTag, pkgcataloging.ImageTag`, (leaving only `"sbom"`). Those tags are used to select default catalogers for image and directory scans. But now the user can just re-enable this using the selection configuration, like `syft --select-catalogers +sbom-cataloger`
