### ISSUE TITLE
Question regarding the secrets cataloger

### ISSUE THREAD

**Issue by tomerse-sg** [anchore/syft#1954]
**What would you like to be added**:
I've tried to use the secrets cataloger, and I saw it can only be used via the power-user command.
When I run it, I saw the message - 
DEPRECATED: This command will be removed in v1.0.0
is it possible to create a separate command in order to use the secrets cataloger?
**Why is this needed**:
will be able to look for sensitive data leak

**Comment by wagoodman** [comment]
Almost all features of the power-user command will be accessible from the root command around syft 1.0. The secrets cataloger is the exception here -- after further discussion we've decided that there are other tools for this and it is generally out of scope for the functionality of generating SBOMs, which is the primary purpose of syft. 

I'm going to close this for now since it answers the question on the issue, however, feel free to continue the conversation here or open another issue for other questions 👍 .
