### ISSUE TITLE
purl missing from report

### ISSUE THREAD

**Issue by jagusztinl** [anchore/syft#216]
**What happened**:
Runned syft to produce BOM 

**What you expected to happen**:
All dependencies should contain purl.

**How to reproduce it (as minimally and precisely as possible)**:
 syft . -o cyclonedx

**Anything else we need to know?**:
Attached the BOM without purl for tomcat embedded core for example (attached the output)

**Environment**:
- syft version (use `syft version -v`):
0.2.0 buildversion 10.08

- OS (e.g: `cat /etc/os-release` or similar):
RHEL [7.6]

[bom.zip](https://github.com/anchore/syft/files/5369701/bom.zip)

**Comment by wagoodman** [comment]
Thanks for reporting @jagusztinl . The java cataloger currently only creates a purl when POM metadata is available within the discovered jar (https://github.com/anchore/syft/blob/main/syft/pkg/java_metadata.go#L36), we should be trying to craft a purl for other kinds of artifacts as well.

**Comment by spiffcs** [comment]
Thanks for filling the bug here!

Our approach is to populate a PURL whenever we have the correct data to do so. If there are specific cases where we are generating an empty string where the information for the package does exist please file that separately to this ticket. 

I'm going to close this issue in favor of more specific reports since we cannot guarantee everything always for all images. We can however act on the issues where a specific PURL is not generated when correct metadata is provided.
