### ISSUE TITLE
format syft-json is not printing the json in beautified format

### ISSUE THREAD

**Issue by tomerse-sg** [anchore/syft#2418]
**What happened**:
Since 0.98.0 I see that when I use -o json format it print the stdout json not in beautified json.
**What you expected to happen**:
keep the old behaviour (like in 0.94.0)
**Steps to reproduce the issue**:
for example ubuntu-20.04
./syft-94 docker-archive:~/Desktop/Git/ubuntu-20.04.tar -o syft-json
./syft-98 docker-archive:~/Desktop/Git/ubuntu-20.04.tar -o syft-json
**Anything else we need to know?**:
Helps to understand better the results.
**Environment**:
- Output of `syft version`: 0.98.0
- OS (e.g: `cat /etc/os-release` or similar): mac 14

**Comment by willmurphyscode** [comment]
Hi @tomerse-sg thanks for the report!

Since SBOMs are sometimes very large, the disk space saved by defaulting to compact JSON helps a lot of users. There are a couple of ways to turn this back on:

* Set the environment variable `SYFT_FORMAT_PRETTY` to `true`, like this: `SYFT_FORMAT_PRETTY=true syft -o json busybox:latest`
* Pipe the output through `jq`, like `syft -o json busybox:latest | jq .` - I do this a lot, because it works for any command that writes valid JSON to stdout, not just on syft.
* Make a config file, for example at `~/.syft.yaml`, that turns this setting on:
``` yaml
format:
  pretty: true
```

**Comment by tomerse-sg** [comment]
hi @willmurphyscode ,
thanks for the answer.
can you please let me know where can I find the main changes done between the schemas of 0.94.0 and 0.98.0?
