### ISSUE TITLE
Do not put version in release filename

### ISSUE THREAD

**Issue by 0xDagal** [anchore/syft#2485]
I would like to be able to download directly the latest version of syft without making two requests. Is it possible on github if the path is like `https://github.com/${ORG}/${REPO}/release/latest/download/${FILENAME}`

For example here, I am looking at the version 0.100.0, I am a Linux user with x86_64 and I use the tgz so I would like the filename to be `syft_linux_amd64.tar.gz` instead of `syft_0.100.0_linux_amd64.tar.gz`.

_Sent from my FP3 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by tgerla** [comment]
Hi, thanks for the suggestion! I will run it by the team to see if we can add a file without a version number to the list of assets. In the meantime, here are a couple of things that might help:

- Our install.sh script for syft and grype has some mechanisms to find the latest version
- I found a generalized tool to solve this problem: https://github.com/dvershinin/lastversion
- And a long and varied discussion of a bunch of different ways to accomplish this: https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

**Comment by tgerla** [comment]
Hi there, after discussing this we are going to go ahead and close this issue since there are some suitable workarounds and generating a release artifact without a version number attached has some potential bad side effects if you are unsure of what's inside the release. Please let us know if you need any more help with the suggested workarounds. Thank you!

**Comment by 0xDagal** [comment]
No problem it was more of a suggestion than anything else and I used a workaround, thanks
