### ISSUE TITLE
[Feature] Syft for 32 bits ARM arch

### ISSUE THREAD

**Issue by dukelaar** [anchore/syft#2704]
A release of syft for ARM32 :)

If not possible the process for manual compilation of syft with 32 bits ARM architecture.

**Comment by tgerla** [comment]
Hey @dukelaar, thanks for the request. We haven't tested this, but you can try compiling a 32-bit version of Syft by checking the source out of GitHub and running:

```GOOS=linux GOARCH=arm go build -o syft-arm32 cmd/syft/main.go
```

You should end up with a 32-bit binary called syft-arm32. Please let us know how it goes--we are curious to see how well this works on a 32-bit system.

**Comment by of-many-devices** [comment]
I've just tested this (cos I needed it too).
It required updating my golang-go package (1.19-1.21)
Then it built successfully with the command above.

Then managed to run the syft-arm32 executable on an arm32 filesystem but I had to --select-catalogers "-elf-package" because without this the syft process was OOM killed:
[  561.632097] Out of memory: Killed process 2472 (syft) total-vm:787712kB, anon-rss:559840kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:626kB oom_score_adj:0

SBOM generated looked alright to my untrained eye.

The only other thing I noticed was that the syft version was reported as "not provided":
syft --version
syft [not provided]

**Comment by tgerla** [comment]
That's great, @of-many-devices, thank you for the feedback. I believe the "[not provided]" version is expected since you are building from source.

**Comment by tgerla** [comment]
Hey all, since we've got a way to build a 32-bit version and it seems to work, I will go ahead and close this issue. If you find any problems running in 32 bits, please let us know. We suspect the OOM kill is legitimate, due to constrained system resources but please let us know if we're wrong. Thanks!

**Comment by willmurphyscode** [comment]
@of-many-devices https://github.com/anchore/syft/releases/tag/v1.3.0 has some real memory efficiency improvements; you may be able to run with the elf-binary-package-cataloger enabled now.
