### ISSUE TITLE
layers attribute in image is sorted from upper layer to base layer

### ISSUE THREAD

**Issue by tomerse-sg** [anchore/syft#2742]
**What would you like to be added**:
are the layers sorted by hierarchy? on what the order is based on?
**Why is this needed**:
can be helpful in order to understand when a package was first added \ when was removed for example.
**Additional context**:
I'm talking about syft json output:
```
      "layers": [
        {
          "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
          "digest": "sha256:701ccb11c0525a289459678e1ef3e9269b62737fafb033db91061ae53a0e9c1e",
          "size": 65675231
        }
```

**Comment by wagoodman** [comment]
The layers are ordered as they are in the underlying container image. If running `docker inspect`, the same order as the  `RootFS` field, this also corresponds to the order of commands in the dockerfile (which can be seen with `docker history`).


I'll close this for now since I think this answers the overall question on layer sorting, however, feel free to reach out if you have more questions.
