### ISSUE TITLE
Analysis of "docker" image fails

### ISSUE THREAD

**Issue by Overcolor** [anchore/syft#287]
**What happened**:
I tried to scan *docker:20.10.0-rc2-git*, but Syft wanted to pull *20.10.0-rc2-git*:
`[0002] ERROR failed to catalog: could not fetch image '20.10.0-rc2-git': pull failed: Error response from daemon: pull access denied for 20.10.0-rc2-git, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**What you expected to happen**:
Analysis of the *docker:20.10.0-rc2-git* image.

**How to reproduce it (as minimally and precisely as possible)**:
```
docker pull docker:20.10.0-rc2-git
syft docker:20.10.0-rc2-git
```
**Anything else we need to know?**:
The same error occurs with Grype.

**Environment**:
- Output of `syft version`:
Application:   syft
Version:       0.9.2
BuildDate:     2020-12-03T21:40:41Z
GitCommit:     f87c59b4eb5d5b1396dcc8ad06a07a0706c4b7c5
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.14.12
Compiler:      gc
- OS (e.g: `cat /etc/os-release` or similar):
Ubuntu 20.04.1

**Comment by pvnovarese** [comment]
fails the same way with any tag in the `docker` repo

slightly different failure if you try `docker` with no tag:

```
pvn@gyarados ~# syft docker
 ✔ Loaded image
[0009] ERROR failed to catalog input: could not fetch image 'docker': tarball must contain only a single image to be used with tarball.Image
```

**Comment by luhring** [comment]
Hi there, thanks for submitting this! You're absolutely right, we need to make an adjustment here.

For completeness, here's what's going on. Syft (and grype) allow users to specify "schemes" in their input string, as a means of directing the tool with an explicit strategy for parsing their input. You can see our schemes by running `syft help`, for example:

```
...
You can also explicitly specify the scheme to use:
    syft docker:yourrepo/yourimage:tag          explicitly use the Docker daemon
    syft docker-archive:path/to/yourimage.tar   use a tarball from disk for archives created from "docker save"
    syft oci-archive:path/to/yourimage.tar      use a tarball from disk for OCI archives (from Podman or otherwise)
...
```

Of course, "docker" is not just a syft scheme, it's the name of a valid container image, which a user might want to inspect.

Our schemes interpretation logic needs to be improved. Given the understanding of a scheme as an overriding, explicit mechanism, one might think that this would be the solution:

```
syft docker:docker:20.10.0-rc2-git
```

But alas, this fails, too.

As it turns out, the following solution _does_ work, but it's not intended that this be the "right way" to inspect the "docker" Docker image:

```
syft docker:docker:docker:20.10.0-rc2-git
```

**Comment by luhring** [comment]
@pvnovarese The latter case you mentioned ("tarball must contain only a single image...") is in the same ballpark, and it's captured as its own issue here: https://github.com/anchore/grype/issues/215

**Comment by spiffcs** [comment]
I'll open a separate issue about schemes so we can talk about that during the architecture refactor.
