### ISSUE TITLE
License is not recognized as SPDX license ID

### ISSUE THREAD

**Issue by HaKAtWork** [anchore/syft#3185]
**What happened**:

- I created a CycloneDX-JSON from a jar-File
- The resulting license information was:
"licenses": [
        {
          "license": {
            "name": "http://www.apache.org/licenses/LICENSE-2.0.txt"
          }
        }
      ],

- I have imported the file into the latest version of Dependency-Track
- Dependency Track treats this license information as “unresolved” because it is not a SPDX license ID

**What you expected to happen**:
Resolving the license information as SPDX license ID:
"licenses": [
        {
          "license": {
            "id": "Apache-2.0"
          }
        }
      ]

**Steps to reproduce the issue**:

- Download the jar-File https://repo1.maven.org/maven2/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar
- syft scan "accessors-smart-1.2.jar" -o cyclonedx-json=accessors-smart.json
- Have a look at the license information

**Comment by willmurphyscode** [comment]
Hi @HaKAtWork, thanks very much for the bug report! We are tracking this same issue over at https://github.com/anchore/syft/issues/3186, so I'm closing this issue as a duplicate, but please follow https://github.com/anchore/syft/issues/3186 and if you have any questions let us know over there. (Your issue was actually opened first :) but our notes from investigating the bug are over on 3186).
