### ISSUE TITLE
Provide some control over what scanning method is used.

### ISSUE THREAD

**Issue by ScottChapman** [anchore/syft#321]
It is clear that scanning folders produces different results than scanning images. For nodejs this appears to be because the lock files are scanned instead. this will produce different results and the fidelity of the results (lacking license info) are also different.

**Comment by spiffcs** [comment]
@ScottChapman We've done a lot of work on this as you can see in #465. There are lots of closed issue allowing people to configure which scanning method is used, which catalogers are selected, and the general shape/inclusion of the SBOM. If there are other suggestions you have please let us know otherwise closing the issue here for now!
