### ISSUE TITLE
Add file metadata cataloger

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#335]
Add a new "power-user" command configuration to capture metadata for each file in an image, including:
- File content digests, with selectable digest algorithms (md5, sha1, sha256 at least)
- File mode
- UID
- GID

Configuration should support:
- Allow for enable/disable of the cataloger as a whole
- Takes a scope option as configuration (default: bind to user config/default)
- Should be able to specify zero or more digest algorithms (default: none)
- Should be able to specify a list of globs to capture metadata information for (default: “**”)

JSON Presentation:
- Adds a new “fileMetadata” section that is a list of objects, each object should have a file path, a layer, and the associated metadata.

**Comment by luhring** [comment]
One thought on the "Configuration should support" section: are all of these items necessary for the MVP of this feature? My understanding is we're intentionally not committing to how we're exposing this functionality to users yet; and instead, for now, our goal is to satisfy a need by one particular downstream consumer — Anchore Engine. If Anchore Engine doesn't need a given piece of configurability, I'd suggest we defer adding it for now, so that we don't introduce more dimensions we need to test, and more scope that takes our time in the short term.
