### ISSUE TITLE
Remove strong distro type

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#342]
Today there is a `distro.Type` that is not internally used within syft (but is within `grype`).  We should consider starting to trust raw os-release data and pass it through to the JSON presenters. We should also consider removing this `distro.Type` type from syft and move it to grype.

**Additional context**:
This is from a discussion from https://anchorecommunity.slack.com/archives/C019BUXV7R6/p1614950344012600 and https://github.com/anchore/syft/pull/341

**Comment by alfredodeza** [comment]
Currently `syft` looks into a few places for OS detection including `/etc/os-release`. For all the locations it looks it attempts to correlated them to pre-defined types. 

Since `syft` doesn't require an accurate OS for creating the SBOM, and at least the `/etc/os-release` parsing has proven robust so far, it would be ideal to loosen the constraint of requiring a type to match against the parsed OS.

That would help support other OSs that implement packages (or packaging methods) that are similar - if not identical as other supported OSs. 

Pull requests like https://github.com/anchore/syft/pull/341 wouldn't be needed either, alleviating the maintenance part. I anticipate there will be more demand for those types of detection and reporting.

**Comment by spiffcs** [comment]
Now that #496 has been merged we're no longer limiting the distro output to the select distros in the type enum. 

The next step here is to remove type completely and put the onus on grype to match `id => type`. 

There are a few places to look to get this working.

0s-release parse https://github.com/anchore/syft/blob/2f99a35f51dde8c84443ce038b71a748439cf83b/syft/distro/identify.go#L124-L142

In the above we probably want to add name to the information being parsed. This way we can have[name, id, version, id_like]

ID ==> Type mapping
https://github.com/anchore/syft/blob/9acabb83078acb8cc825a8438b8cea5cbcb4c731/syft/distro/type.go#L43-L59

This is where we do the `id => type` mapping. We should move this into grype.

Proposed new distro data structure so we can have both id and name. This should also reflect in the presenter logic.
```
{
  "id": ""
  "name": "",
  "version": "",
  "idLike": ""
 }
```
