### ISSUE TITLE
Image manifest digest computation is not done on the exact manifest from the registry, so it may differ from that reported from the registry

### ISSUE THREAD

**Issue by zhill** [anchore/syft#376]
**What happened**:
The manifest digests (and thus image digest) produced by Syft may not match the digest presented by the image registry in cases where the manifest in the registry uses whitespace formatting. It appears that syft is either removing formatting, or is using a source to read the manifest that is not the byte-correct manifest from the registry source.

**What you expected to happen**: They should match so that images can be correctly correlated between local image and the image in the registry

**How to reproduce it (as minimally and precisely as possible)**:

Run syft on an example image that is not available locally yet: `syft docker:anchore/kai:v0.2.1 -o json`
Review the manifestDigest section:
`sha256:7099fc930d02ddfaa43e8e22666ee89d0098b19d978fcee82a5fa9f240123e3b`

View the registry digest: https://hub.docker.com/r/anchore/kai/tags?page=1&ordering=last_updated
See the DockerHub digest is:
`sha256:6b3ec3b3df94d9852bd7bc437c9e56da961b3f4d406a842444751f2c84c16de1`

We can confirm with _skopeo_ that this image is not a multi-arch image and that the digest reported from the registry is not the digest of a manifest-list document, but is the image manifest itself (see below for the skopeo outputs to confirm).

**Anything else we need to know?**:
```
skopeo inspect docker://anchore/kai:v0.2.1
{
    "Name": "docker.io/anchore/kai",
    "Digest": "sha256:6b3ec3b3df94d9852bd7bc437c9e56da961b3f4d406a842444751f2c84c16de1",
    "RepoTags": [
        "latest",
        "v0.1.0",
        "v0.2.0",
        "v0.2.1"
    ],
    "Created": "2021-02-19T23:16:33.358034981Z",
    "DockerVersion": "20.10.2+azure",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:90fb8c3989507148c3a96471e155b63cbb388412c26e7ba3a640b933317d695f"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}
```

```
skopeo inspect --raw docker://anchore/kai:v0.2.1
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1454,
      "digest": "sha256:75bf0c5be4170a652edfc91c59f3555bb9a1fea003bda2d7d40f9c0f05d2a3a9"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 8677212,
         "digest": "sha256:90fb8c3989507148c3a96471e155b63cbb388412c26e7ba3a640b933317d695f"
      }
   ]
}%
```

```
syft docker:anchore/kai:v0.2.1 -o json
{
 "artifacts": [],
 "source": {
  "type": "image",
  "target": {
   "userInput": "anchore/kai:v0.2.1",
   "imageID": "sha256:75bf0c5be4170a652edfc91c59f3555bb9a1fea003bda2d7d40f9c0f05d2a3a9",
   "manifestDigest": "sha256:7099fc930d02ddfaa43e8e22666ee89d0098b19d978fcee82a5fa9f240123e3b",
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "tags": [
    "anchore/kai:v0.2.1"
   ],
   "imageSize": 28295168,
   "scope": "Squashed",
   "layers": [
    {
     "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
     "digest": "sha256:fd1a86ac46a13d450dbb7712e0bc6be56db49eaaa940734c9c3f554f8f73b325",
     "size": 28295168
    }
   ],
   "manifest": "eyJzY2hlbWFWZXJzaW9uIjoyLCJtZWRpYVR5cGUiOiJhcHBsaWNhdGlvbi92bmQuZG9ja2VyLmRpc3RyaWJ1dGlvbi5tYW5pZmVzdC52Mitqc29uIiwiY29uZmlnIjp7Im1lZGlhVHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5kb2NrZXIuY29udGFpbmVyLmltYWdlLnYxK2pzb24iLCJzaXplIjoxNDU0LCJkaWdlc3QiOiJzaGEyNTY6NzViZjBjNWJlNDE3MGE2NTJlZGZjOTFjNTlmMzU1NWJiOWExZmVhMDAzYmRhMmQ3ZDQwZjljMGYwNWQyYTNhOSJ9LCJsYXllcnMiOlt7Im1lZGlhVHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5kb2NrZXIuaW1hZ2Uucm9vdGZzLmRpZmYudGFyLmd6aXAiLCJzaXplIjoyODI5NjcwNCwiZGlnZXN0Ijoic2hhMjU2OmZkMWE4NmFjNDZhMTNkNDUwZGJiNzcxMmUwYmM2YmU1NmRiNDllYWFhOTQwNzM0YzljM2Y1NTRmOGY3M2IzMjUifV19",
   "config": "eyJhcmNoaXRlY3R1cmUiOiJhbWQ2NCIsImNvbmZpZyI6eyJIb3N0bmFtZSI6IiIsIkRvbWFpbm5hbWUiOiIiLCJVc2VyIjoiIiwiQXR0YWNoU3RkaW4iOmZhbHNlLCJBdHRhY2hTdGRvdXQiOmZhbHNlLCJBdHRhY2hTdGRlcnIiOmZhbHNlLCJUdHkiOmZhbHNlLCJPcGVuU3RkaW4iOmZhbHNlLCJTdGRpbk9uY2UiOmZhbHNlLCJFbnYiOlsiUEFUSD0vdXNyL2xvY2FsL3NiaW46L3Vzci9sb2NhbC9iaW46L3Vzci9zYmluOi91c3IvYmluOi9zYmluOi9iaW4iXSwiQ21kIjpudWxsLCJJbWFnZSI6InNoYTI1NjpmZmMyMzJlYmJhYWMwNjJkZWVlYjZiNDIzMDkxNDVjODMyNjNiNTY5MDUyNDRhZGJhMTFkN2M5MjhhODc2NjJjIiwiVm9sdW1lcyI6bnVsbCwiV29ya2luZ0RpciI6IiIsIkVudHJ5cG9pbnQiOlsiL2thaSJdLCJPbkJ1aWxkIjpudWxsLCJMYWJlbHMiOm51bGx9LCJjb250YWluZXJfY29uZmlnIjp7Ikhvc3RuYW1lIjoiIiwiRG9tYWlubmFtZSI6IiIsIlVzZXIiOiIiLCJBdHRhY2hTdGRpbiI6ZmFsc2UsIkF0dGFjaFN0ZG91dCI6ZmFsc2UsIkF0dGFjaFN0ZGVyciI6ZmFsc2UsIlR0eSI6ZmFsc2UsIk9wZW5TdGRpbiI6ZmFsc2UsIlN0ZGluT25jZSI6ZmFsc2UsIkVudiI6WyJQQVRIPS91c3IvbG9jYWwvc2JpbjovdXNyL2xvY2FsL2JpbjovdXNyL3NiaW46L3Vzci9iaW46L3NiaW46L2JpbiJdLCJDbWQiOlsiL2Jpbi9zaCIsIi1jIiwiIyhub3ApIENPUFkgZmlsZTo4ZTY5OGFmNzIyMjJiYjU1M2RjZGY3NWMwY2Q4YjQ1YjlkMDAwYzliMjdkOGQ1ZTE1YzNmOWZmMGRhOTg2N2IzIGluIC8gIl0sIkltYWdlIjoic2hhMjU2OmZmYzIzMmViYmFhYzA2MmRlZWViNmI0MjMwOTE0NWM4MzI2M2I1NjkwNTI0NGFkYmExMWQ3YzkyOGE4NzY2MmMiLCJWb2x1bWVzIjpudWxsLCJXb3JraW5nRGlyIjoiIiwiRW50cnlwb2ludCI6WyIva2FpIl0sIk9uQnVpbGQiOm51bGwsIkxhYmVscyI6bnVsbH0sImNyZWF0ZWQiOiIyMDIxLTAyLTE5VDIzOjE2OjMzLjM1ODAzNDk4MVoiLCJkb2NrZXJfdmVyc2lvbiI6IjIwLjEwLjIrYXp1cmUiLCJoaXN0b3J5IjpbeyJjcmVhdGVkIjoiMjAyMS0wMi0xOVQyMzoxNjozMi43MDY1NTk0MTNaIiwiY3JlYXRlZF9ieSI6Ii9iaW4vc2ggLWMgIyhub3ApICBFTlRSWVBPSU5UIFtcIi9rYWlcIl0iLCJlbXB0eV9sYXllciI6dHJ1ZX0seyJjcmVhdGVkIjoiMjAyMS0wMi0xOVQyMzoxNjozMy4zNTgwMzQ5ODFaIiwiY3JlYXRlZF9ieSI6Ii9iaW4vc2ggLWMgIyhub3ApIENPUFkgZmlsZTo4ZTY5OGFmNzIyMjJiYjU1M2RjZGY3NWMwY2Q4YjQ1YjlkMDAwYzliMjdkOGQ1ZTE1YzNmOWZmMGRhOTg2N2IzIGluIC8gIn1dLCJvcyI6ImxpbnV4Iiwicm9vdGZzIjp7InR5cGUiOiJsYXllcnMiLCJkaWZmX2lkcyI6WyJzaGEyNTY6ZmQxYTg2YWM0NmExM2Q0NTBkYmI3NzEyZTBiYzZiZTU2ZGI0OWVhYWE5NDA3MzRjOWMzZjU1NGY4ZjczYjMyNSJdfX0="
  }
 },
 "distro": {
  "name": "",
  "version": "",
  "idLike": ""
 },
 "descriptor": {
  "name": "syft",
  "version": "0.14.0"
 },
 "schema": {
  "version": "1.0.2",
  "url": "https://raw.githubusercontent.com/anchore/syft/main/schema/json/schema-1.0.2.json"
 },
 "artifactRelationships": []
}
```

The manifest reported by Syft (I saved syft output in _syft_kai.json_):
```
jq .source.target.manifest -r syft_kai.json | base64 -d
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"mediaType":"application/vnd.docker.container.image.v1+json","size":1454,"digest":"sha256:75bf0c5be4170a652edfc91c59f3555bb9a1fea003bda2d7d40f9c0f05d2a3a9"},"layers":[{"mediaType":"application/vnd.docker.image.rootfs.diff.tar.gzip","size":28296704,"digest":"sha256:fd1a86ac46a13d450dbb7712e0bc6be56db49eaaa940734c9c3f554f8f73b325"}]}%
```

Note no whitespaces compared to the skopeo raw output. The skopeo-presented manifest digest matches its output:
```
skopeo inspect --raw docker://anchore/kai:v0.2.1 | shasum -a 256
6b3ec3b3df94d9852bd7bc437c9e56da961b3f4d406a842444751f2c84c16de1  -
```

**Environment**:
- Output of `syft version`:
```
syft version
Application:   syft
Version:       0.14.0
BuildDate:     2021-03-20T16:47:03Z
GitCommit:     26a4dd36a8932c7867fcdd6296f50643be30f8a6
GitTreeState:  clean
Platform:      darwin/amd64
GoVersion:     go1.14.15
Compiler:      gc

**Comment by luhring** [comment]
This looks like more than a whitespace or formatting issue, based on what I'm seeing.

In Syft's "reconstructed manifest", which can be seen by piping Syft JSON into `| jq .source.target.manifest -r | base64 -d`, I'm noticing that the layers' `"mediaType"` values end in **`gzip`**, despite the fact that the `"size"` values match exactly the size (in bytes) of the **uncompressed** layer (observable by checking the `layer.tar` files output by `docker save ...`, or by un-gzipping the layer blobs obtained by `skopeo copy ... oci:...`). It's not currently clear to me how the layer digest reported in Syft's reconstructed manifest is generated.

So in addition to possible whitespace differences, Syft's reconstructed manifest **disagrees** with the registry's manifest in both the **_size_** and **_digest_** for the layers listed.

I don't see how it's possible for Syft to have access to the original registry manifest content when it's accessing an image representation via the `docker save` process.

**Question:** _Is this reconstructed manifest useful for any reason?_ If it is, I'd suggest we add an _additional_ field for a discovered registry manifest (and manifest digest) if we find it, rather than replacing this one. This way, it would be explicit when you have a manifest/digest that you can depend on when accessing the registry. If the reconstructed manifest is never useful, we can remove it, and conditionally provide manifest/digest fields when we know we have the exact manifest from the registry.

**Comment by zhill** [comment]
I agree in disambiguating a retrieved manifest and a computed manifest. This is the fundamental problem between analysis of the output of a specific instantiation of the image and the image content as presented from the registry.

To tool cannot make general guarantees but we should at least provide one method by which those guarantees can be made so that users who require that consistency can use that mechanism reliably even if it requires additional preparation in the execution environment. For example, a force-pull mode that would download the image from the registry instead of using local docker-daemon even if available, but could give the consistency guarantees.

**Comment by luhring** [comment]
@zhill @wagoodman

In our discussion the other day, we said that if adding the `registry:` scheme explicitly to user input for Syft results in the Syft JSON output reliably showing the **_registry's_** manifest and manifest digest, no further action was needed on this ticket right now.

👍  We believe **this has been achieved** as of #382 — thus, we won't prioritize more work on this issue until we hear otherwise. We expect to publish a release shortly that includes this existing work.

As a reminder, we don't believe it's possible for Syft to show the true registry manifest/digest in some cases, most notably of which is our primary usage scenario, where Syft gets the image from the Docker daemon.

**Comment by luhring** [comment]
Closing per the above message based on not seeing any objections to the currently implemented solution. We can re-open later if needed.
