### ISSUE TITLE
Improve discovery of app.jar packaging (self-executing Jars)

### ISSUE THREAD

**Issue by hev** [anchore/syft#413]
**What would you like to be added**:
Users of popular java frame work spring often package thier app as /app.jar.  This JAR file usually has a shell script prepended to them, ostensibly to enable them to configure their environment at runtime.  The script headers lead us to believe that it comes from the Spring framework / build tools, and we have little reason to believe that this is an uncommon way to distribute/deploy JAR files.

**Why is this needed**:
Steps to reproduce
syft packages [redacted]

Expected result
spring-core should appear in the output, as it's bundled in the /app.jar in the image

**Additional context**:

**Comment by cburgess** [comment]
I would add that we would expect more than just spring-core in the output. In Anchore Enterprise 2.x the entire shar and all included JAR files would be unpacked and cataloged.

**Comment by luhring** [comment]
Interesting! I've never heard of that, but I'm a Java-ignoramus.

@hev Do we have an example? Or somewhere in Engine/Enterprise we can point to for this behavior? (I'll also look around)

**Comment by hev** [comment]
@zhill perhaps you can help guide how engine has handled this in the past?

**Comment by zhill** [comment]
For clarity this is the error: 

`WARN cataloger ‘java-cataloger’ failed to parse entries (Location<id=3557 RealPath=“/app.jar” VirtualPath=“/app.jar” Layer=“sha256:f8af747a7e09cfc41068429dadb08fa4a60de206eef9bade4bd4cba826d515ae”>): unable to read files from java archive: unable to open zip archive (/var/folders/9t/4dv6njks73b3x3krqm3fxxnm0000gn/T/syft-jar-contents-896927952/archive): zip: not a valid zip file
`

Engine uses a regular zip file processor for jars, it looks like the zip lib used by Syft isn't able to handle this type of file.

**Comment by wagoodman** [comment]
Yeah, I think we can support this functionality.

Currently the golang stdlib `archive/zip` package [does not support this](https://github.com/golang/go/issues/10464). It looks like there's been a patch to incorporate into go [ready since 2015](https://github.com/philwebb/go/commit/b1b65c2b4cd85f1a67c3c5c8cf40254030c7cab4), but there is no PR and I think there is a way forward without needing to change the stdlib.

We could infer the archive length from the [end of central directory record](https://en.wikipedia.org/wiki/ZIP_(file_format)#End_of_central_directory_record_(EOCD)), create a new `io.ReaderAt` via [`io.SectionReader`](https://golang.org/pkg/io/#SectionReader) that is bounded to only the archive based on the length from the ECOD, and create a new zip reader via `zip.NewReader()` (instead of `zip.OpenReader`). We'd need to make certain that the underlying reader passed to the `SectionReader` is closed after each use since there is no `Close()` operation available from a `zip.Reader`.
