### ISSUE TITLE
Add Nix Cataloger

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#462]
It would be ideal to be able to identify and catalog [Nix](https://nixos.org/) packages.

**Comment by juliosueiras** [comment]
![Screenshot from 2021-12-18 19-47-36](https://user-images.githubusercontent.com/3680302/146659598-e79f225c-4b61-4fdf-b578-8f75529b0a54.png)
![Screenshot from 2021-12-18 19-52-25](https://user-images.githubusercontent.com/3680302/146659605-8e77e37b-f794-4184-a40f-857a3570abcc.png)

Doing a basic nix-store cataloger, since drv files doesn't get include the docker build when you are using dockerTools(which is more common one for nix users compare to in-docker nix-build)

**Comment by wagoodman** [comment]
@juliosueiras that's awesome --shout out if you want an extra helping hand! Up to you if you wanted to open up a draft PR and swarm on bug squashing or closing the gap on what's left 👍

**Comment by nikolaishields** [comment]
I am also interested in collaborating or lending any support I can in SBOM generation via nix through syft.

**Comment by ghuntley** [comment]
Would be also interested in seeing support for nix :)

**Comment by juliosueiras** [comment]
sound good

**Comment by juliosueiras** [comment]
created the draft PR #1107 , which is based on the Deb cataloger, there is still the bug of certain stuff(that doesn't have version) not splitting correctly

**Comment by ghuntley** [comment]
Legend.

**Comment by juliosueiras** [comment]
a quick note: the drv(json file refer from the earlier comment chain) is something that only exist on the build machine, not the finish artifact, so if an image is build via dockerTools family, then it will not contain any drvs, only the resulting store entries

**Comment by wagoodman** [comment]
quick note: the above PR has been merged into the in-repo feature branch `add-nix-cataloger` for further development (tip of the hat to @juliosueiras  for the original implementation). I'll see what I can do to get this in.
