### ISSUE TITLE
Licenses output includes extraneous junk

### ISSUE THREAD

**Issue by khuey** [anchore/syft#463]
Example output from `syft  packages -o cyclonedx ubuntu:focal`

```xml
    <component type="library">
      <name>libp11-kit0</name>
      <version>0.23.20-1ubuntu0.1</version>
      <licenses>
        <license>
          <name>BSD-3-Clause</name>
        </license>
        <license>
          <name>ISC</name>
        </license>
        <license>
          <name>ISC+IBM</name>
        </license>
        <license>
          <name>permissive-like-automake-output</name>
        </license>
        <license>
          <name>same-as-rest-of-p11kit</name>
        </license>
      </licenses>
      <purl>pkg:deb/ubuntu/libp11-kit0@0.23.20-1ubuntu0.1?arch=amd64</purl>
    </component>
```

Whatever inputs are being used here are dirty and not being validated against the SPDX list apparently.

```
> syft version
Application:   syft
Version:       0.19.1
BuildDate:     2021-06-30T17:32:06Z
GitCommit:     fee35dd1753308fc887da744de5d0c66947c7493
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.16.5
Compiler:      gc
```

**Comment by bureado** [comment]
Those strings certainly come from [the input](https://changelogs.ubuntu.com/changelogs/pool/main/p/p11-kit/p11-kit_0.23.20-1ubuntu0.1/copyright). In a Debian-based system, I'd consider it a bug for `syft` not to report the strings as-found in a `copyright` file. If the strings in `p11-kit` are inaccurate or meaningless, I'd consider that a bug against `p11-kit`, but I'd give the [Copyright Format](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-specification) a read first as I haven't looked deeply into that. Then there's a separate question of whether, in CycloneDX, SPDX license identifiers are the only accepted license identifiers; this doesn't seem to be the case [nor the direction](https://cyclonedx.org/news/cyclonedx-v1.3-released/#copyright-and-license-evidence) and it seems the team chose `<name>` (instead of the possible `<id>`) as a compromise solution since that [seems to accommodate](https://github.com/CycloneDX/specification/blob/master/schema/bom-1.3.xsd#L427) this case.

**Comment by khuey** [comment]
Alright, that's fair.
