### ISSUE TITLE
Deduplicate found components or include more information

### ISSUE THREAD

**Issue by PapoyEdits** [anchore/syft#492]
Perhaps related to https://github.com/anchore/syft/issues/32

Basically, after running Syft on an image primarily containing NPM packages I got a pretty large SBOM, and when looking into it, I saw a lot of duplicates, anywhere between the range of 1-10 duplicates for a lot of packages. Some of course were different versions of a particular package, but many times it was the exact same, ex. 

(CycloneDX format)
```
<component type="library">
      <name>1to2</name>
      <version>1.0.0</version>
      <licenses>
        <license>
          <name>MIT</name>
        </license>
      </licenses>
      <purl>pkg:npm/1to2@1.0.0</purl>
    </component>
    <component type="library">
      <name>1to2</name>
      <version>1.0.0</version>
      <licenses>
        <license>
          <name>MIT</name>
        </license>
      </licenses>
      <purl>pkg:npm/1to2@1.0.0</purl>
    </component>
```

My assumption is that Syft is picking up sub-dependencies or some such, which I'd say is a good thing. 

But it would be nice if there could either be a flag that we could set to avoid getting these duplicates, or if the components could contain some additional information to make their inclusion meaningful.

**Comment by spiffcs** [comment]
@PapoyEdits thanks for the issue! Do you have an image we can use to reproduce the duplicates? I think there is some identifying information in the core syft data format that we can reflect up into cyclonedx to give more nuance to these findings. Having a concrete example to start from helps so we make sure we're fulfilling your need rather than just adding all of the possible data we can from the start.
