### ISSUE TITLE
Extract Java or any other "language/framework" version from image

### ISSUE THREAD

**Issue by PapoyEdits** [anchore/syft#524]
**What would you like to be added**: I would like Syft to be able to extract the Java version (or really any of the "large" language/framework versions like Java, Dotnet, Python etc.) from the image that is scanned when using a base-image

**Why is this needed**: Since these versions are pretty core to the image, it makes sense to have them in the generated SBOM as well

**Additional context**:
Asked this question in the syft-help Slack channel, and was asked to file an issue, https://anchorecommunity.slack.com/archives/C019BUXV7R6/p1632984127013300

I'm currently using the adoptopenjdk/openjdk11:alpine-jre base-image and Syft to extract packages from our custom image, which works great, but the Java version is not currently being extracted which is quite important in our SBOMs. 

At the moment I extract it by running the image and parsing the output from java -version into a PURL which we then convert into a cyclonedx format component, but ideally we could avoid that slightly cumbersome step.

`$ docker run adoptopenjdk/openjdk11:alpine-jre java -version 2>&1 | grep version | sed 's/ version / /;s/\"//g' | awk -F" " '{print "pkg:generic/oracle/"$1"@"$2}'`
Which produces: pkg:generic/oracle/openjdk@11.0.12

As mentioned, it would be great if there could be support for not just Java but others like Dotnet and Python as well, though I understand that it might be difficult to support everything and anything.

**Comment by bureado** [comment]
Interesting problem. If I think of npm or pip for a moment, syft will find those libraries but I don't think syft can assert which runtime those libraries use or which runtime will any arbitrary program that calls those libraries will use.

If the interpreter/runtime is in the image as a Linux package, it will know that (possibly also for openjdk in the alpine case you mention above, but less reliably so in other scenarios such as "distroless") but it's no guarantee that's the stack that will end up being used at runtime, seen venv and friends.

I do think there's value for example in having a bag of semantically relevant annotations in the `syft` output. For example, in a system with `nodejs`, I would like to know the version of `npm` and the hashes of that binary. Possibly the same for `maven`, `cpan`, etc., since those seem to be relevant to the supply chain security/dependency acquisition of the system being evaluated. I'd be particularly interested in those annotations in cases where the hash of the binary does not match the hash expected in, say, a package manifest.
