### ISSUE TITLE
Syft not yielding entire Output

### ISSUE THREAD

**Issue by stefanm8** [anchore/syft#671]
**What happened**:

Trying to scan filesystem project results into uncomplete data

**What you expected to happen**:
See the full list of vendors

**How to reproduce it (as minimally and precisely as possible)**:
```
syft .
```

**Anything else we need to know?**:
Trying to run syft on a project will return 
```
$ syft .
 ✔ Indexed .
 ✔ Cataloged packages              [2504 packages]
 ```
 
 Though if I count the output yields:
 
 ```
 $ syft . | wc -l
 ✔ Indexed .
 ✔ Cataloged packages              [2504 packages]

    1537
 ```

Also it seems that if I use grep I can retrieve the dependencies not shown.

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by wagoodman** [comment]
@stefanm8 Good question. I think the main reason why you are seeing this is because the table output is being used. The table output only shows a little bit of information, so we deduplicate the rows based on only the information shown. You may have a package referenced in multiple locations for the same package name, version, and ecosystem.

If you use the JSON output (`-o json`) you should see all of your packages under the `artifacts` section. Shout out if you are still seeing inconsistencies!

**Comment by stefanm8** [comment]
@wagoodman Thanks, it solved the issue.
