### ISSUE TITLE
Distro of alpine:edge is busybox

### ISSUE THREAD

**Issue by cdupuis** [anchore/syft#691]
```
 syft registry:alpine:edge -o json
```

returns 

```
 "distro": {
  "name": "busybox",
  "version": "1.33.1",
  "idLike": ""
 }
```

I _think_ that should say `alpine 3.15`

```
21:01 $ docker run -it alpine:edge
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0_alpha20210804
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
/ # 
```

**Comment by wagoodman** [comment]
Thanks for reporting! I think I see why this may be happening. The `VERSION_ID` doesn't follow semver rules:
```
$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0_alpha20210804
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
I think this is leading to an error being raised instead of a distro object here: https://github.com/anchore/syft/blob/3f305aa6cd75c79709d93d91135452d00fff4249/syft/distro/distro.go#L23-L26

When this occurs the next OS identifier is used, in this case, busybox. Since busybox is installed within alpine, then that distro parser returns a valid distro.

This brings up a couple points that could lead to change:
1. We probably shouldn't assume that the version of a distro is semver compliant. Or we should make some attempts to clean the version before giving up (or have a safe fallback).
2. Do we even need a rich semver object on the distro object? This sounds like something that grype really needs, not syft. And if thats the case, is further data for https://github.com/anchore/syft/issues/342
3. We should be able to express that the distro cannot be busy box if there is an `/etc/os-release` file on the system (today we only check for the binary).

**Comment by kzantow** [comment]
I believe this has been addressed -- running the latest version of Syft against alpine:edge (`syft registry:alpine:edge -o json`) results in:
```
 "distro": {
  "prettyName": "Alpine Linux edge",
  "name": "Alpine Linux",
  "id": "alpine",
  "versionID": "3.17_alpha20221110",
  "homeURL": "https://alpinelinux.org/",
  "bugReportURL": "https://gitlab.alpinelinux.org/alpine/aports/-/issues"
 },
```

I'm going to close this as fixed, but if you continue to have issues please reopen!
