### ISSUE TITLE
Cannot install grype on air-gapped RHEL system.

### ISSUE THREAD

**Issue by cddrury** [anchore/syft#713]
**What happened**:
Tried to install grype on air-gapped Red Hat Enterprise Linux 7.6 system. As root, ran the install.sh script with no parameters and script immediately tries to connect to GitHub for latest tag. Added GRYPE_DB_AUTO_UPDATE="false" to environment but that does not stop the script from trying to connect to GitHub.
**What you expected to happen**:
I expected the grype binary to be installed to /usr/local/bin/ but there does not seem to be a switch to disable the installation script from trying to download files from GitHub.
**How to reproduce it (as minimally and precisely as possible)**:
Download Code as a zip file.
Move zip file to air-gapped system.
Unzip file to directory.
cd to unzipped location.
as root, execute ./install.sh
install.sh fails.
**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar):
syft is not installed.
OS RHEL 7.6

**Comment by luhring** [comment]
Hi @cddrury, the `install.sh` script is not designed to work in an air-gapped environment — its implementation finds and retrieves a release asset from **github.com** over the Internet. (`GRYPE_DB_AUTO_UPDATE` is an environment variable that configures Grype itself, not the installation script.)

However, installing Grype in an air-gapped environment should be straightforward. Grype is a static binary. So once you obtain the right binary for your platform from Grype's [releases page](https://github.com/anchore/grype/releases), you can simply extract the `grype` binary from the downloaded package, and put that `grype` binary in your system's `PATH`.

Since Grype uses a vulnerability database, if you're working in an air-gapped environment, you'll also need to ensure the database is in place. See the [documentation on managing Grype's database](https://github.com/anchore/grype#managing-grypes-database), and let me know if you have any remaining questions on how to do this.

**Comment by cddrury** [comment]
@luhring, the link to the Grype binary (RPM) was the key to get the software installed and running. If the README.md could be updated to point to the releases page, I believe that would help users like me install the binary on the air-gapped system and run the program after installing the database and using the environment variable to prevent Grype from trying to use the Internet to update. 

Your answer basically solves the issue and in my opinion closes this issue.

Thank you.
