### ISSUE TITLE
unable to catalog dpkg package=/var/lib/dpkg/status

### ISSUE THREAD

**Issue by foolm00n** [anchore/syft#733]
**What happened**:
1 error occurred:
	* unable to catalog dpkg package=/var/lib/dpkg/status: bad installed-size value="2400MB": strconv.Atoi: parsing "2400MB": invalid syntax

**What you expected to happen**:
Didn't expect the error. The size of /var/lib/dpkg/status is actually 2.4MB not "2400MB"
It runs without errors on another machine with very similar configuration.

**How to reproduce it (as minimally and precisely as possible)**:
As root, run syft dir:/ -v -o json --file sbom.json

**Anything else we need to know?**:
Without verbose mode, syft gets stuck and hangs at "Cataloging packages [packages: 0]" stage

**Environment**:
- Output of `syft version`:
```
Application:   syft
Version:       0.34.0
BuildDate:     2021-12-22T21:15:39Z
GitCommit:     7f8cb0bd8068709982ef23e931e1ceaa2dfac955
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.16.12
Compiler:      gc
```

- OS (e.g: `cat /etc/os-release` or similar):
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by jonasagx** [comment]
Thanks for posting this bug @foolm00n
There seem to be two problems:

1. dpkg meta data
It looks like your `/var/lib/dpkg/status` has a package where the installed-size field is not just an integer, so Syft should accept file sizes with scale suffixes, e.g. 1MB. I can't reproduce it on my debian boxes since `installed-size` probably comes from a dpkg application meta-data. Would you mind sharing which package has the `installed-size` with `MB` or any other value that is not simply an integer?

2. hanging problem
We are investigating cases where it happens. Also keep in mind that scanning all your file system might take awhile.

**Comment by foolm00n** [comment]
@jonasagx Thank you very much for your reply.
I have found the problem in /var/lib/dpkg/status
```
/var/lib/dpkg/status
Package: edrawmax
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 2400MB
Maintainer: SHENZHEN EDRAW SOFTWARE CO.LTD
Architecture: amd64
Version: 11.1.2
Description: All-in-one diagramming software.
Homepage: https://www.edrawsoft.com/
```

When I changed the Installed-Size to 2400000 it worked fine. I'm not sure why that package didn't specify the size according to the convention. Every other package did not have a suffix, just an integer value.

This has also fixed the hanging issue!

Thank you again for you help.
