### ISSUE TITLE
absent metadata for the root directory

### ISSUE THREAD

**Issue by errordeveloper** [anchore/syft#861]
**What would you like to be added**:

Metadata catalogger repors modes and ownership of all directories, however it currently skips `/`. 

**Why is this needed**:

This would be usefull if someone wantted to ensure that root directory has sansible permissions.

**Comment by wagoodman** [comment]
Good catch on the edge case --the root is always already in the filetree, so there is a bug where metadata for that entry will be skipped. I can put in a PR to fix this.

One clarifying question: since the output for the file metadata cataloger only reports files (and not directories), is the output you were noticing this from from the golang API directly? or from somewhere else? 

There have been recent changes to this behavior as well --can you include which version of syft you were using?

**Comment by wagoodman** [comment]
I've made an update to fix the directory resolver, however, I think the image resolvers would need a little more thought / investigation. The root directory is a mount, so for the directory resolver this isn't a problem since the indexing is occurring on the system so the mount details can be observed. For image analyses this isn't true --the mount only occurs when we run a container, however, we are looking at the underlying image tars to figure what the filesystem will look like when creating a container. I can double check this, but I think the underlying image tars tend not to have any entries for `/` itself, only the contents of root. This means (baring double checking the last statement) that it shouldn't be possible to get metadata for `/` for images directly.

**Comment by errordeveloper** [comment]
I can see how this might be tricky. I wonder if the OCI spec cover the permissions on the directory...?

**Comment by spiffcs** [comment]
>  I can double check this, but I think the underlying image tars tend not to have any entries for / itself, only the contents of root. This means (baring double checking the last statement) that it shouldn't be possible to get metadata for / for images directly.

I just checked this. The underlying image do no have entries for `/`. Currently I can't find a way to get the metadata or permissions from the `/` directory through the OCI specification.

I think without this we are unable to surface this information.

**Comment by spiffcs** [comment]
@errordeveloper I'm going to close this for now after searching for ways to surface this information and not coming up with a complete solution. If you find anything or know of a way you would like to see these permissions shown let me know and I can reopen the issue and pursue more aspects on the implementation

**Comment by errordeveloper** [comment]
> @errordeveloper I'm going to close this for now after searching for ways to surface this information and not coming up with a complete solution. If you find anything or know of a way you would like to see these permissions shown let me know and I can reopen the issue and pursue more aspects on the implementation

Absolutely makes sense, thanks for looking into it!
