### ISSUE TITLE
Flag to strip package name in rpm/deb packages pURL export

### ISSUE THREAD

**Issue by arthur-hav** [anchore/syft#984]
**What would you like to be added**:

I am requesting to be added to Syft, as an option, a config option or flag to disable pURL namespaces for deb and rpm packages.

**Why is this needed**:

Syft builds rpm pURL as pkg:rpm/distro/package_name while the tool we use (dependency track, which scans vulns based on https://ossindex.sonatype.org/) expects pkg:rpm/package_name

Consequently, over a vast number of rpm packages used in our infrastructure, no vulnerability is found whereas there are many to be found stripping the namespace

pURLs can include or not the distro name for rpm, the specification seem interpreted both ways by various actors. In order to adapt both paradigm we would request a customizable export.

**Comment by spiffcs** [comment]
Thanks for filling the issue @arthur-hav! Just coming back to this issue and seeing it's been 3 months. Has dependency track updated their software to consume the valid PURLS produced by syft?

I am hesitant to accept a modification to allow users to drop this field only because more information is better, and I believe that downstream consumers should be the ones with the burden of updating to consume valid PURL for match purposes.

We also don't want to get into a world where Syft is gnerating a list of PURL where optional fields are omitted in some while others are more verbose.

Let me know if you still are not getting results from dependency track and maybe we can file and issue with them

**Comment by arthur-hav** [comment]
Your argument seem reasonable; I'm all for adapting downstream and/or using adapters in the middle to avoid any unnecessary data cropping.

I have no idea about any possible change as I happened to have swapped employers and no longer follow the issue.

Thank you for your time to come back to me nonetheless.
